# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21a3e2d17117acfcc14d7091cd7b3f651f47adb96493b9d41c9a19fafc4e6d501312114d7331f5756d478751aee18d7d985799a1fd8ac9eb41f26df96da091e0

test:
  secret_key_base: 06ec6a2c5d0cc143a61129a42e43d2e7d32d239459a5445a7c35d96228db230e5214540c9dd0172b3cc722817458e452e61498e518c14e983392f76f5efe0b09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
